[pytest]
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
testpaths = tests
addopts = --strict-markers -p no:cacheprovider --no-header
filterwarnings =
    ignore::DeprecationWarning
